name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cargo Make
      run: cargo install --force cargo-make
    - name: Rust Test
      run: cargo make test
    - name: Julia test
      run: cargo make jl_test
